[package]
name = "PayPerPrompt"
version = "1.0.0"
authors = ["PayPerPrompt Team"]

[addresses]
PayPerPrompt = "_"
std = "0x1"
aptos_framework = "0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-addresses]
PayPerPrompt = "0x42"
