[package]
name = "PayPerPrompt"
version = "1.0.0"
authors = ["PayPerPrompt Team"]
edition = "2024.beta"

[addresses]
PayPerPrompt = "_"
std = "0x1"

[dependencies.MoveStdlib]
git = "https://github.com/move-language/move.git"
rev = "main"
subdir = "language/move-stdlib"

[dev-addresses]
PayPerPrompt = "0x42"
